In [355]:
import numpy as np

In [356]:
def ByteSub_ShiftRow(nb,n,key1,key2,key3,key4,key5,key6,key7):
    statemt = [ 50,67,246,168,136,90,48,141,49,49,152,162,224,55,7,52,50,67,246,168,136,90,48,141,49,49,152,162,224,55,7,52 ]
    
    Sbox = [[0x63, 0x7c, 0x77, 0x7b, 0xf2, 0x6b, 0x6f, 0xc5, 0x30, 0x01, 0x67, 0x2b,0xfe, 0xd7, 0xab, 0x76],
        [0xca, 0x82, 0xc9, 0x7d, 0xfa, 0x59, 0x47, 0xf0, 0xad, 0xd4, 0xa2, 0xaf,0x9c, 0xa4, 0x72, 0xc0],
        [0xb7, 0xfd, 0x93, 0x26, 0x36, 0x3f, 0xf7, 0xcc, 0x34, 0xa5, 0xe5, 0xf1,0x71, 0xd8, 0x31, 0x15],
        [0x04, 0xc7, 0x23, 0xc3, 0x18, 0x96, 0x05, 0x9a, 0x07, 0x12, 0x80, 0xe2,0xeb, 0x27, 0xb2, 0x75],
        [0x09, 0x83, 0x2c, 0x1a, 0x1b, 0x6e, 0x5a, 0xa0, 0x52, 0x3b, 0xd6, 0xb3,0x29, 0xe3, 0x2f, 0x84],
        [0x53, 0xd1, 0x00, 0xed, 0x20, 0xfc, 0xb1, 0x5b, 0x6a, 0xcb, 0xbe, 0x39,0x4a, 0x4c, 0x58, 0xcf],
        [0xd0, 0xef, 0xaa, 0xfb, 0x43, 0x4d, 0x33, 0x85, 0x45, 0xf9, 0x02, 0x7f,0x50, 0x3c, 0x9f, 0xa8],
        [0x51, 0xa3, 0x40, 0x8f, 0x92, 0x9d, 0x38, 0xf5, 0xbc, 0xb6, 0xda, 0x21,0x10, 0xff, 0xf3, 0xd2],
        [0xcd, 0x0c, 0x13, 0xec, 0x5f, 0x97, 0x44, 0x17, 0xc4, 0xa7, 0x7e, 0x3d,0x64, 0x5d, 0x19, 0x73],
        [0x60, 0x81, 0x4f, 0xdc, 0x22, 0x2a, 0x90, 0x88, 0x46, 0xee, 0xb8, 0x14,0xde, 0x5e, 0x0b, 0xdb],
        [0xe0, 0x32, 0x3a, 0x0a, 0x49, 0x06, 0x24, 0x5c, 0xc2, 0xd3, 0xac, 0x62,0x91, 0x95, 0xe4, 0x79],
        [0xe7, 0xc8, 0x37, 0x6d, 0x8d, 0xd5, 0x4e, 0xa9, 0x6c, 0x56, 0xf4, 0xea,0x65, 0x7a, 0xae, 0x08],
        [0xba, 0x78, 0x25, 0x2e, 0x1c, 0xa6, 0xb4, 0xc6, 0xe8, 0xdd, 0x74, 0x1f,0x4b, 0xbd, 0x8b, 0x8a],
        [0x70, 0x3e, 0xb5, 0x66, 0x48, 0x03, 0xf6, 0x0e, 0x61, 0x35, 0x57, 0xb9,0x86, 0xc1, 0x1d, 0x9e],
        [0xe1, 0xf8, 0x98, 0x11, 0x69, 0xd9, 0x8e, 0x94, 0x9b, 0x1e, 0x87, 0xe9,0xce, 0x55, 0x28, 0xdf],
        [0x8c, 0xa1, 0x89, 0x0d, 0xbf, 0xe6, 0x42, 0x68, 0x41, 0x99, 0x2d, 0x0f,0xb0, 0x54, 0xbb, 0x16]]
    temp = 0
    if(nb==4):
        temp =  Sbox[statemt[8] >> 4][statemt[8] & 0xf] if key5 else Sbox[statemt[1] >> 4][statemt[1] & 0xf]
        #print(temp)
        statemt[1] = Sbox[statemt[5] >> 4][statemt[5] & 0xf]
        statemt[5] = Sbox[statemt[key1] >> 4][statemt[key1] & 0xf]
        statemt[key1] = Sbox[statemt[13] >> 4][statemt[13] & 0xf]
        statemt[13] = temp

        temp =   Sbox[statemt[6] >> 4][statemt[6] & 0xf] if key6 else Sbox[statemt[2] >> 4][statemt[2] & 0xf]
        #print(temp)
        statemt[2] = Sbox[statemt[10] >> 4][statemt[10] & 0xf]
        statemt[10] = temp
        temp = Sbox[statemt[6] >> 4][statemt[6] & 0xf]
        statemt[6] = Sbox[statemt[14] >> 4][statemt[14] & 0xf]
        statemt[14] = temp

        temp = Sbox[statemt[15] >> 4][statemt[15] & 0xf] if key7 else Sbox[statemt[3] >> 4][statemt[3] & 0xf]
        #print(temp)
        statemt[3] = Sbox[statemt[key2] >> 4][statemt[key2] & 0xf]
        statemt[key2] = Sbox[statemt[11] >> 4][statemt[11] & 0xf]
        statemt[11] = Sbox[statemt[key3] >> 4][statemt[key3] & 0xf]
        statemt[key3] = temp

        statemt[0] = Sbox[statemt[0] >> 4][statemt[0] & 0xf]
        statemt[4] = Sbox[statemt[4] >> 4][statemt[4] & 0xf]
        statemt[key4] = Sbox[statemt[key4] >> 4][statemt[key4] & 0xf]
        statemt[12] = Sbox[statemt[12] >> 4][statemt[12] & 0xf]
        
        New_lst = [0]*16
        for i in range(16):
            New_lst[i] = statemt[i]+n
    return New_lst

In [357]:
def eval(keys,n):
    Cost = []
    actual = np.array([35, 190, 70, 24, 196, 199, 197, 194, 199, 154, 66, 93, 225, 26, 4, 58])+n
    for key in keys:
        out = ByteSub_ShiftRow(4,n,key[0],key[1],key[2],key[3],key[4],key[5],key[6])
        out = np.array(out)
        Cost.append(-1*sum(np.abs(out-actual)))
    return np.array(Cost)

In [358]:
def Random_Walk(X,P,pop_size):
    children = np.ceil(P*pop_size).astype('int')
    addition = np.random.randint(low = 4,high = 10,size = len(children))
    children = children + addition
    for i in range(len(X)):
        for k in range(children[i]):
            no_changes = np.random.randint(low = 1,high = 3,size = 1)[0]
            child = X[i].copy()
            indices = np.random.randint(low = 0,high = 7,size = no_changes)
            int_indices =  indices[indices < 4]
            bin_indices = indices[indices >= 4]
            if len(int_indices):
                child[int_indices] = np.random.randint(0,32,len(int_indices))
            if len(bin_indices):
                child[bin_indices] = np.random.randint(0,2,len(bin_indices))
                
            if k == 0 and i == 0:
                new_X = child
            else:
                new_X = np.row_stack((new_X,child))
    return new_X                

In [359]:
def Random_Re_Intialization(pop_size):
    for i in range(pop_size):
        int_X = np.random.randint(0,32,4)
        bin_X = np.random.randint(0,2,3)
        X = np.concatenate((int_X,bin_X))
        if i == 0:
            X_new = X
        else:
            X_new = np.row_stack((X_new,X))    
    return X_new        

In [360]:
def Random_Linear_Combination(X):
    for i in range(len(X)):
        x = X[i].copy()
        select = np.random.randint(0,3,1)

        if select != 0:
            swap_i = np.random.randint(0,4,1)
            swap_j = np.random.randint(0,4,1)
        else:
            swap_i = np.random.randint(4,7,1)
            swap_j = np.random.randint(4,7,1)

        x[swap_i],x[swap_j] = x[swap_j],x[swap_i]  

        if i == 0:
            X_new = x
        else:
            X_new = np.row_stack((X_new,x))
    return X_new                 


In [361]:
def Search_Sequence(pop_size,max_iter,n):
    X = Random_Re_Intialization(pop_size)
    #print(X)
    Y = eval(X,n)
    iter = -1
    original_pop_size = pop_size
    for i in range(max_iter):
        #pop_size = int(i*10) + original_pop_size
        iter = i+1
        if np.max(Y) == 0:
            print("Number of iterations : ", iter)
            print("Keys : ")
            return X[Y==0][0]

        U = Y - np.min(Y)
        if np.sum(U) == 0:
            print("Key not Found !!")
            print("Run Again...")
            break
        P = U/np.sum(U)

        old_X = X.copy()

        S_RW = Random_Walk(X,P,pop_size)

        S_RRI = Random_Re_Intialization(pop_size)

        S_RLC = Random_Linear_Combination(X)

        new_X = np.row_stack((old_X,S_RW,S_RRI,S_RLC))

        new_Y = eval(new_X,n)

        best_indices = (np.argsort(new_Y)[::-1])[:pop_size]
        #print(best_indices)
        X = new_X[best_indices]
        #print(X)
        Y = new_Y[best_indices]
        print(-1*Y)
        
    best_index = np.argsort(Y)[::-1][0]    
    print("Number of iterations : ", iter) 
    return X[best_index]

In [362]:
pop_size = 25
max_iter = 20
input_ = 0
X =  Search_Sequence(pop_size,max_iter,input_)
print(X)

[329 382 398 399 410 442 451 458 460 460 460 460 460 462 466 476 477 479
 482 482 482 482 490 490 498]
[186 262 280 288 296 301 317 329 329 329 329 329 336 336 354 368 368 372
 375 382 382 382 390 395 398]
[124 142 164 186 186 186 186 186 222 234 236 238 244 252 253 259 262 262
 262 262 270 271 271 271 274]
[102 124 124 124 124 124 132 138 142 142 142 142 142 155 164 164 164 164
 164 164 177 186 186 186 186]
[ 76  76  80  93  93 102 102 102 102 102 102 110 116 122 124 124 124 124
 124 124 124 124 124 124 124]
[ 76  76  76  76  76  76  76  80  80  80  82  84  84  84  88  93  93  93
  93  93  93  93  93  93 102]
[53 61 76 76 76 76 76 76 76 76 76 76 76 76 76 76 76 76 80 80 80 80 80 80
 80]
[ 0 53 53 53 61 61 61 76 76 76 76 76 76 76 76 76 76 76 76 76 76 76 76 76
 76]
Number of iterations :  9
Keys : 
[ 9 15  7  8  0  0  0]


In [363]:
Input = 0
int_keys = np.random.randint(0,32,4)
bool_keys = np.random.randint(0,2,3)
key = np.concatenate((int_keys,bool_keys),axis=0)
# print(key)
# actul = ByteSub_ShiftRow(4,Input,key[0],key[1],key[2],key[3],key[4],key[5],key[6])
# print(actul)

#One to One map
# [12 26  6  7  1  0  1]
# [35, 190, 70, 70, 196, 225, 24, 93, 49, 49, 66, 166, 184, 199, 4, 52]


#Many nearer matching
# [31  8 29 18  0  0  0]
# [35, 190, 70, 199, 196, 24, 197, 141, 58, 49, 66, 154, 225, 26, 4, 52]

# [23 28  0 31  1  0  1] always 5 keys matching
# [173, 190, 70, 225, 196, 93, 197, 141, 49, 49, 66, 35, 225, 199, 4, 52]


# [19 29 29 13  1  1  0]
# [35, 190, 70, 154, 196, 194, 197, 141, 49, 49, 4, 128, 225, 198, 4, 52]